### ISSUE TITLE
[offb_controller] Discuss and finalise overall control algorithm

### ISSUE THREAD

**Issue by serverwentdown** [makerforceio/autoforce#2]

**Comment by solderneer** [comment]
Isn't this already roughly finalized. I thought you and Isaac discussed it?

**Comment by serverwentdown** [comment]
I didn't discuss it with isaac yet but i want to formally sit down in person and think of any issues we may encounter with the proposed design.

**Comment by serverwentdown** [comment]
Should be quick.
